#!/usr/bin/env bash

source "${library_dir}/logging.sh"

set -o errexit
set -o nounset
set -o pipefail


readonly args=($@)

readonly config_key="${args[0]:?"missing config_key and config_value"}"
readonly config_value="${args[1]:?"missing config_value"}"



create_config_file() {
  debug "create_config_file"
  local config_dir_name=${config_file_path%/*}
  mkdir --parents "${config_dir_name}"
  touch "${config_file_path}"

  echo "created an configuration file called '${config_file_path}'"
  echo "If you want to use another file, set an environment variable called HOPLA_CONFIG_FILE."
}

add_configuration_to_config_file() {
  debug "add_configuration_to_config_file"

  # TODO: implement replacement of pre-existing configuration
  echo "${config_key}=${config_value}" >> "${config_file_path}"
}


main() {
  if [[ ! -f ${config_file_path} ]] ; then
      create_config_file
  fi
  add_configuration_to_config_file
}
main



