#!/usr/bin/env bash

source "${library_dir}/logging.sh"

create_auth_file() {
  debug "create_auth_file"
  auth_dir_name=${auth_file_path%/*}
  mkdir -p "${auth_dir_name}"
  touch "${auth_file_path}"

  echo "created an authentication file called '${auth_file_path}'"
  echo 'If you want to use another file, set an environment variable called HOPLA_AUTH_FILE.'
}

if [[ ! -f ${auth_file_path} ]] ; then
  create_auth_file
fi


write_credential_file() {
  debug "write_credential_file"

  read -r -p "Please enter your habitica 'User ID': "   habitica_user_id
  read -r -p "Please enter your habitica 'API Token': " habitica_api_token

  echo "auth_file_user_id=${habitica_user_id}"     >  "${auth_file_path}"
  echo "auth_file_api_token=${habitica_api_token}" >> "${auth_file_path}"
}
write_credential_file


